### ISSUE TITLE
Deletion of labels

### ISSUE THREAD

**Issue by julifan** [spcl/perf-taint#28]
When one tainted variable is initialized based on another tainted variable, but they are not semantically dependent after that, it would be helpful to have the possibility to delete the corresponding label (stating their dependency on another).

**Comment by mcopik** [comment]
@julifan I pushed to master a fix to this issue.

See the unit test for details: https://github.com/spcl/perf-taint/blob/master/tests/unit/api/delete_label.cpp#L77
